<?php

namespace AppBundle\Repository;

/**
 * LocationEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationEventRepository extends \Doctrine\ORM\EntityRepository
{
}
