<?php

namespace AppBundle\Repository;

/**
 * OrganizerEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizerEventRepository extends \Doctrine\ORM\EntityRepository
{
}
