<?php

namespace AppBundle\Repository;

/**
 * PictureEmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureEmplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
