<?php

namespace AppBundle\Repository;

/**
 * TypeEmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEmplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
